In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import style
import datetime as dt
import seaborn as sns
sns.set_style("whitegrid")

In C:\Users\Malavika\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Malavika\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Malavika\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In C:\Users\Malavika\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Malavika\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Malavika\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The keymap.all_axes rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Malavika\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The animation.avconv_path rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Malavika\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The animation.avconv_args rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.

In [ ]:
##In this file, we find the correlation between the difference between the actual price and facebook's price, on those dates when the difference between the two is more than 200, with other macroeconomic data.
##The implication is that some correlation coefficients are high. So it's worthwhile investigating what additional data comes into play here, which makes prophet inaccurate.

In [2]:
df1= pd.read_csv('df1.csv', parse_dates=['Date'])
df1 = df1.rename(columns = {"Date":"ds","Close":"y"}) 
df1

,ds,y,tby,ffr,fta,eps,div,per,une,rus,wti,ppi,rfs,vix
0,2005-06-20,1216.10,4.11,3.04,812235.0,84.81,1.76,18.8026,5.0,641.840027,59.19,154.3,343998.0,148.30
1,2005-06-21,1213.61,4.06,3.04,812235.0,84.81,1.76,18.8026,5.0,641.039978,58.90,154.3,343998.0,149.00
2,2005-06-22,1213.88,3.95,3.04,811179.0,84.81,1.76,18.8026,5.0,643.450012,58.27,154.3,343998.0,148.40
3,2005-06-23,1200.73,3.96,3.04,811179.0,84.81,1.76,18.8026,5.0,634.119995,59.23,154.3,343998.0,150.50
4,2005-06-24,1191.57,3.92,3.04,811179.0,84.81,1.76,18.8026,5.0,630.409973,59.63,154.3,343998.0,152.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3874,2020-12-24,3703.06,0.94,0.09,7404039.0,97.20,1.61,38.2297,6.7,2003.949951,48.18,200.5,535972.0,23.85
3875,2020-12-28,3735.36,0.94,0.09,7404039.0,97.20,1.61,38.2297,6.7,1996.250000,47.50,200.5,535972.0,23.60
3876,2020-12-29,3727.04,0.94,0.09,7404039.0,97.20,1.61,38.2297,6.7,1959.359985,47.85,200.5,535972.0,24.70
3877,2020-12-30,3732.04,0.93,0.09,7363351.0,97.20,1.61,38.2297,6.7,1979.989990,48.24,200.5,535972.0,23.75
3878,2020-12-31,3756.07,0.93,0.09,7363351.0,95.72,1.58,38.2297,6.7,1974.859985,48.35,200.5,535972.0,23.60

In [3]:
import datetime as datetime
ctf_date = datetime.datetime(2020, 3, 1)
df = df1.loc[df1.ds < ctf_date , ].copy()
df

,ds,y,tby,ffr,fta,eps,div,per,une,rus,wti,ppi,rfs,vix
0,2005-06-20,1216.10,4.11,3.04,812235.0,84.81,1.76,18.8026,5.0,641.840027,59.19,154.3,343998.0,148.30
1,2005-06-21,1213.61,4.06,3.04,812235.0,84.81,1.76,18.8026,5.0,641.039978,58.90,154.3,343998.0,149.00
2,2005-06-22,1213.88,3.95,3.04,811179.0,84.81,1.76,18.8026,5.0,643.450012,58.27,154.3,343998.0,148.40
3,2005-06-23,1200.73,3.96,3.04,811179.0,84.81,1.76,18.8026,5.0,634.119995,59.23,154.3,343998.0,150.50
4,2005-06-24,1191.57,3.92,3.04,811179.0,84.81,1.76,18.8026,5.0,630.409973,59.63,154.3,343998.0,152.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3663,2020-02-24,3225.89,1.38,1.58,4171570.0,135.28,1.79,25.3952,3.5,1628.099976,51.36,196.7,525810.0,20.15
3664,2020-02-25,3128.21,1.33,1.58,4171570.0,135.28,1.79,25.3952,3.5,1571.900024,49.78,196.7,525810.0,21.95
3665,2020-02-26,3116.39,1.33,1.58,4158637.0,135.28,1.79,25.3952,3.5,1552.760010,48.67,196.7,525810.0,22.45
3666,2020-02-27,2978.76,1.30,1.58,4158637.0,135.28,1.79,25.3952,3.5,1497.869995,47.17,196.7,525810.0,26.60
3667,2020-02-28,2954.22,1.13,1.58,4158637.0,135.28,1.79,25.3952,3.5,1476.430054,44.83,196.7,525810.0,26.10

In [4]:
from datetime import datetime
p = 0.9
# Train around 90% of dataset 
# cutoff = int((p*len(df)//100)*100)
cutoff = int(p*len(df))
df_train = df[:cutoff].copy()
df_test = df.drop(df_train.index).copy()

print(df_train, df_test)

             ds        y   tby   ffr        fta     eps   div      per  une  \
0    2005-06-20  1216.10  4.11  3.04   812235.0   84.81  1.76  18.8026  5.0
1    2005-06-21  1213.61  4.06  3.04   812235.0   84.81  1.76  18.8026  5.0
2    2005-06-22  1213.88  3.95  3.04   811179.0   84.81  1.76  18.8026  5.0
3    2005-06-23  1200.73  3.96  3.04   811179.0   84.81  1.76  18.8026  5.0
4    2005-06-24  1191.57  3.92  3.04   811179.0   84.81  1.76  18.8026  5.0
...         ...      ...   ...   ...        ...     ...   ...      ...  ...
3296 2018-08-30  2901.13  2.86  1.91  4218914.0  131.51  1.84  22.2526  3.8
3297 2018-08-31  2901.52  2.86  1.91  4218914.0  134.20  1.82  22.2526  3.8
3298 2018-09-04  2896.72  2.90  1.95  4218914.0  134.20  1.82  22.3482  3.7
3299 2018-09-05  2888.60  2.90  1.95  4208496.0  134.20  1.82  22.3482  3.7
3300 2018-09-06  2878.05  2.88  1.95  4208496.0  134.20  1.82  22.3482  3.7

              rus    wti    ppi       rfs     vix
0      641.840027  59.19  154.3  343998.0  148.30
1      641.039978  58.90  154.3  343998.0  149.00
2      643.450012  58.27  154.3  343998.0  148.40
3      634.119995  59.23  154.3  343998.0  150.50
4      630.409973  59.63  154.3  343998.0  152.00
...           ...    ...    ...       ...     ...
3296  1732.349976  70.25  203.4  501913.0   14.55
3297  1740.750000  69.84  203.4  501913.0   13.98
3298  1733.380005  69.82  203.6  500362.0   14.25
3299  1727.650024  68.69  203.6  500362.0   14.60
3300  1714.469971  67.81  203.6  500362.0   15.20

[3301 rows x 14 columns]              ds        y   tby   ffr        fta     eps   div      per  une  \
3301 2018-09-07  2871.68  2.94  1.95  4208496.0  134.20  1.82  22.3482  3.7
3302 2018-09-10  2877.13  2.94  1.95  4208496.0  134.20  1.82  22.3482  3.7
3303 2018-09-11  2887.89  2.98  1.95  4208496.0  134.20  1.82  22.3482  3.7
3304 2018-09-12  2888.92  2.97  1.95  4210812.0  134.20  1.82  22.3482  3.7
3305 2018-09-13  2904.18  2.97  1.95  4210812.0  134.20  1.82  22.3482  3.7
...         ...      ...   ...   ...        ...     ...   ...      ...  ...
3663 2020-02-24  3225.89  1.38  1.58  4171570.0  135.28  1.79  25.3952  3.5
3664 2020-02-25  3128.21  1.33  1.58  4171570.0  135.28  1.79  25.3952  3.5
3665 2020-02-26  3116.39  1.33  1.58  4158637.0  135.28  1.79  25.3952  3.5
3666 2020-02-27  2978.76  1.30  1.58  4158637.0  135.28  1.79  25.3952  3.5
3667 2020-02-28  2954.22  1.13  1.58  4158637.0  135.28  1.79  25.3952  3.5

              rus    wti    ppi       rfs    vix
3301  1713.180054  67.73  203.6  500362.0  15.45
3302  1717.469971  67.55  203.6  500362.0  14.75
3303  1718.400024  69.29  203.6  500362.0  14.20
3304  1715.699951  70.37  203.6  500362.0  14.05
3305  1714.319946  68.60  203.6  500362.0  13.42
...           ...    ...    ...       ...    ...
3663  1628.099976  51.36  196.7  525810.0  20.15
3664  1571.900024  49.78  196.7  525810.0  21.95
3665  1552.760010  48.67  196.7  525810.0  22.45
3666  1497.869995  47.17  196.7  525810.0  26.60
3667  1476.430054  44.83  196.7  525810.0  26.10

[367 rows x 14 columns]

In [5]:
from fbprophet import Prophet
pred_periods = int((1-p)* len(df))
fbp = Prophet(daily_seasonality=False)

# fit close price using fbprophet model
fbp.fit(df_train[['ds','y']])
    
 # predict pred_size futures and get the forecast price 
fut = fbp.make_future_dataframe(periods = pred_periods)
forecast = fbp.predict(fut)

Importing plotly failed. Interactive plots will not work.
INFO:numexpr.utils:NumExpr defaulting to 4 threads.
C:\Users\Malavika\Anaconda3\lib\site-packages\pystan\misc.py:399: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif np.issubdtype(np.asarray(v).dtype, float):

In [6]:
df2 = df.copy()
df2['fbsp'] = forecast.yhat
df2['diff'] = df2['y'] - df2['fbsp']

In [21]:
df2 = df2.dropna()
df3 =df2[(df2['diff'] > 200) | (df2['diff' ]< -200) ]

In [22]:
df3

,y,tby,ffr,fta,eps,div,per,une,rus,wti,ppi,rfs,vix,fbsp,diff
ds,,,,,,,,,,,,,,,
2018-01-26,2872.87,2.66,1.41,4441317.0,118.06,1.84,24.4613,4.0,1608.060059,66.27,197.9,491492.0,12.30,2642.676119,230.193881
2018-01-29,2853.53,2.70,1.41,4441317.0,118.06,1.84,24.4613,4.0,1598.109985,65.71,197.9,491492.0,13.55,2641.960040,211.569960
2018-10-24,2656.10,3.10,2.19,4173070.0,136.81,1.80,20.4830,3.8,1468.699951,66.56,204.6,506010.0,20.37,2862.292882,-206.192882
2018-10-26,2658.69,3.08,2.19,4173070.0,136.81,1.80,20.4830,3.8,1483.819946,67.58,204.6,506010.0,21.30,2864.453640,-205.763640
2018-10-29,2641.25,3.08,2.19,4173070.0,136.81,1.80,20.4830,3.8,1477.310059,67.00,204.6,506010.0,21.70,2865.320202,-224.070202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-02-13,3373.94,1.61,1.58,4182689.0,135.28,1.79,25.3952,3.5,1693.739990,51.41,196.7,525810.0,14.83,3170.182786,203.757214
2020-02-14,3380.16,1.59,1.58,4182689.0,135.28,1.79,25.3952,3.5,1687.579956,52.03,196.7,525810.0,14.40,3171.089958,209.070042
2020-02-18,3370.29,1.55,1.58,4182689.0,135.28,1.79,25.3952,3.5,1683.520020,52.10,196.7,525810.0,15.00,3169.916238,200.373762
2020-02-19,3386.15,1.56,1.58,4171570.0,135.28,1.79,25.3952,3.5,1692.569946,53.31,196.7,525810.0,15.39,3171.262187,214.887813
2020-02-27,2978.76,1.30,1.58,4158637.0,135.28,1.79,25.3952,3.5,1497.869995,47.17,196.7,525810.0,26.60,3180.633625,-201.873625

In [23]:
df3.corr()['diff'].sort_values()

ffr    -0.780843
vix    -0.725222
eps    -0.626639
div    -0.575302
une    -0.550951
ppi    -0.429770
tby    -0.423198
fbsp    0.271836
fta     0.319906
rfs     0.465828
wti     0.496055
per     0.846516
y       0.888932
rus     0.920841
diff    1.000000
Name: diff, dtype: float64